# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-json
  - id: check-toml
  - id: check-merge-conflict
  - id: check-added-large-files
- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.42.1
  hooks:
  - id: commitizen
  - id: commitizen-branch
    stages: [push]
- repo: https://github.com/python-poetry/poetry
  rev: '1.6.1'
  hooks:
  - id: poetry-lock
  - id: poetry-check
