version: '3'
services:
  lacebook:
    container_name: lacebook
    build:
      context: ../
      dockerfile: ./docker/docker_build/Dockerfile
    ports:
      - 127.0.0.1:8899:8899
    restart: on-failure
    volumes:
      - ../../:/usr/local/src/python-sdk/:ro
      - $HOME/.lacework.toml:/home/lacework/.lacework.toml
      - /tmp/:/usr/local/src/lacedata/
