name: Run Python Linting/Docstring Linting

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 8 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install poetry
        run: |
          pipx install poetry

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Install dependencies
        run: |
          poetry install

      - name: Lint Docstrings with ruff
        run: |
          poetry run poe lint-docstrings 

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          poetry run poe lint
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          poetry run flake8 . --exclude "jupyter" --count --exit-zero --max-complexity=10 --statistics

