name: Semantic Release

on:
  workflow_dispatch:
    inputs:
      bump_major:
        required: false
        type: choice
        description: should the major version be incremented
        default: 'false'
        options:
          - true
          - false

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install poetry
      run: |
        pipx install poetry

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        cache: 'poetry'

    - name: Install dependencies
      run: |
        poetry check
        poetry lock --no-update
        poetry install --verbose

    - name: Python Semantic Major Release
      if: ${{ inputs.bump_major == 'true' }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "action@github.com"
        semantic-release version --major
        semantic-release publish -D commit_author="github-actions <action@github.com>"
      env:
        GH_TOKEN: ${{secrets.GITHUB_TOKEN}}


    - name: Python Semantic Release
      if: ${{ inputs.bump_major == 'false' }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "action@github.com"
        semantic-release version
        semantic-release publish -D commit_author="github-actions <action@github.com>"
      env:
        GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
